services:
  - name: ecommerce-backend
    type: web
    rootDir: backend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: NODE_VERSION
        value: "18"
